apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.3

certificatesDir: /etc/kubernetes/pki
clusterName: installation-test-2022
imageRepository: k8s.gcr.io
controlPlaneEndpoint: lb-kubernetes.local

apiServer:
  certSANs:
    - lb-kubernetes.local
  timeoutForControlPlane: 4m0s
  extraArgs:
    authorization-mode: "Node,RBAC"
    anonymous-auth: "true"
    #enable-admission-plugins: AlwaysPullImages,DefaultStorageClass

networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  ## weavenet requires: 10.32.0.0/12
  ## flannel requires: 10.244.0.0/16
  ## calico: no sepecific CIDR
  podSubnet: 10.32.0.0/12

